Rails Blog Project: Milestone 8 System RSpec Testing
Profsain/rails-blog pull request #9
Opened 2022-10-10 22:07 UTC by Profsain

### I completed this part of the project by:
- Fixing N+1 loading problem
- Created integrated test for User page
- Created integrated test for Post page
- Push all changes to GitHub and Make a pull request
-

2022-10-10 22:47 UTC, medaminedev66 requested changes
Hi @Profsain  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The repo looks professional.
- There are no linter errors.
- You have a descriptive PR.
- Your code is clean

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-10 22:47 UTC, medaminedev66 commented on spec/system/posts_spec.rb
> +end
- [ ] All the tests fail except one. Please ensure all the tests pass successfully:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/77190203/194962863-53b0718b-c3b2-4c17-83b3-2055963d02ac.png">
<img width="622" alt="image" src="https://user-images.githubusercontent.com/77190203/194962973-e307b866-a634-42a2-8f8f-20036267a7e0.png">

- If you see that I'm missing something or something is not 100% clear, please reach out to me on slack or leave comments in the PR thread.
Remember to tag me in your question so I can receive the notification.

2022-10-10 22:47 UTC, medaminedev66 commented on spec/system/users_spec.rb
> +  end
- [ ] For the users show page, kindly add:
  - Tests that assert you can see a button that lets you view all of a user's posts.
  - Tests that redirects to the user's post's index page when you click on a **see all posts**.

2022-10-10 22:47 UTC, medaminedev66 commented on spec/system/posts_spec.rb
> +
- [ ] For the posts/index page, please add:
* Tests that asserts you can see the first comments on a post.
* Tests that asserts you can see a section for pagination if there are more posts than fit on the view.
* Tests that redirects to the post's show page when you click on a post.

2022-10-10 22:47 UTC, medaminedev66 commented on spec/system/posts_spec.rb
> +  end
- [ ] For the posts/show page, Kindly add:
* Tests that asserts you can see the post's title.
* Tests that asserts you can see who wrote the post.
* Tests that asserts you can see how many comments it has.
* Tests that asserts you can see how many likes it has.
* Tests that asserts you can see the post body.
* Tests that asserts you can see the username of each commentor.
* Tests that asserts you can see the comment each commentor left.

2022-10-11 05:29 UTC, Profsain commented on spec/system/posts_spec.rb
> +end
Thank you for the feedback. When I run the test all the test passes.
I currently have 25 test cases in total.
![sys](https://user-images.githubusercontent.com/32632836/195004324-07df6cc4-6f0d-47dd-bb40-0ff07334b194.jpg)

2022-10-11 05:30 UTC, Profsain commented on spec/system/users_spec.rb
> +  end
I will implement the test required.

2022-10-12 16:52 UTC, julie-ify requested changes
## Hi @Profsain,

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-12 16:52 UTC, julie-ify commented on spec/system/posts_spec.rb
> +      expect(page).to have_text("#{@user.posts_counter} post") if @user.posts_counter > 0
- [ ] This rspec expectation is failing. Kindly fix it. From the error message you need to format from "1 post" to "post: 1".

  ```
  "post: #{@user.posts_counter}"
  ```

  ![ffn](https://user-images.githubusercontent.com/81468675/195402192-8145b8bb-3641-4826-a09a-5d3f5b1aa257.jpg)

2022-10-12 20:56 UTC, Profsain commented on spec/system/posts_spec.rb
> +      expect(page).to have_text("#{@user.posts_counter} post") if @user.posts_counter > 0
Thank you for your feedback.
I will correct it.

2022-10-12 21:42 UTC, merged